### ISSUE TITLE
LinkBot dont works

### ISSUE THREAD

**Issue by WinterNatsu** [PaeP3nguin/LinkBot#2]
Hello PaeP3nguin,

First of all, I want to glad you by your nice job in this project, it was very useful.

My problem is that the extension dont work more... maybe is the new version of chrome, I dont't know.

How can I fix this problem? Any suggestion?

Best Regards

**Comment by PaeP3nguin** [comment]
Oh no! I'll try and see what's going wrong. What version of Chrome do you have?

**Comment by PaeP3nguin** [comment]
Oh and if you have a specific site for where it's not working, that would help too

**Comment by WinterNatsu** [comment]
Currently I'm using Chrome Version 71.0.3578.30, but I think that have almost 6 months that the extension stopped work.

One example that I use is in forums, before, when anybody put a link into a code tag, I was able to click and go to the site... but now, doesn't work more... actually, linkBot did not work for a long time.

Ex.: `www.google.com.br` <- Would Extension recognize this?

**Comment by WinterNatsu** [comment]
Ok, let me see... I searched over the internet for a random site that show the same problem:

http://forum.mypst.com.br/index.php/forum-68/announcement-8-tutorial-de-bbcode-todas-as-tags-explicadas/

(Look at this line "[spoiler]https://www.youtube.com/watch?v=9IbPrk-yuts[/spoiler] <- Vídeo em spoiler" that the extension doesn't work.)

I don't  know if it occours in every forum from "invision community"... but it is it.

Thanks for the attention.

**Comment by PaeP3nguin** [comment]
Oh, I see. By default, LinkBot won't make links out of anything in one of those pre-formatted text blocks. I suppose it's possible to make that configurable but I don't have the time these days :(

**Comment by fucusy** [comment]
@PaeP3nguin I created a PR, https://github.com/PaeP3nguin/LinkBot/pull/5, to address this problem, could you take a look at that?
