### ISSUE TITLE
LinkBot does not always work

### ISSUE THREAD

**Issue by smaragdus** [PaeP3nguin/LinkBot#9]
Hello,

I like **LinkBot** but it does not always work- it fails to linkify certain domains, screens:

- **Example 1**
![LinkBot 1 0 7 - 2019-11-06 - 003](https://user-images.githubusercontent.com/9025757/68256846-f0203580-0039-11ea-857a-828fde615bf2.png)
- **Example 2**
![LinkBot 1 0 7 - 2019-11-06 - 004](https://user-images.githubusercontent.com/9025757/68256869-062df600-003a-11ea-81fa-a3c00987e2c8.png)

You can test **LinkBot** with these pages:

- [Website 1](https://merveilles.town/about/more)
- [Website 2](https://github.com/merveilles/The-Town/blob/master/docs/DOMAIN_BLOCKS.md)

Perhaps you need to update your domain parser.

Regards

**Comment by PaeP3nguin** [comment]
Hey smaragdus you're totally right, the valid domain endings are hard-coded in, because.... people forget to put spaces after their periods a lot :)

Looks like I've got a bunch more to add. Or I can give up and just accept that some missing spaces will cause unwanted links.

**Comment by smaragdus** [comment]
@PaeP3nguin 

> Hey smaragdus you're totally right, the valid domain endings are hard-coded in, because.... people forget to put spaces after their periods a lot :)

Thanks for the confirmation. And yes, from time to time I come across sentences without spaces in between.

> Looks like I've got a bunch more to add. Or I can give up and just accept that some missing spaces will cause unwanted links.

In my opinion it would be a better option to add domains to your list as there would be less false links. Can you get a ready-made list of all possible domains and use it?

Regards

**Comment by PaeP3nguin** [comment]
Added all the TLDs on those pages as a band-aid for now. Eventually I'll probably have to cave and find a big list of every domain and generate the big regex from that :)

Submitted update to the chrome store, might take a few days to be published I would guess.

**Comment by smaragdus** [comment]
@PaeP3nguin 

Thanks for the update. [Chrome Web Store](https://chrome.google.com/webstore/detail/linkbot/chnfcfcbnhloogdohcmjogkklghefofm) is still at version 1.0.7- as far as I know they manually review every update so the update process is slow. Anyway, I am glad that [LinkBot](https://github.com/PaeP3nguin/LinkBot) is still maintained and updated- many useful extensions get abandoned, cease to work and sometimes there are no good alternatives.
